#!/bin/env sh

lb config noauto \
  --color \
  --image-name zerro \
  --debian-installer live \
  --debian-installer-gui false \
  --apt-indices false \
  --apt-recommends false

#git clone https://github.com/AlexanderARodin/debian-live-build.git

#cp -r ./auto/ddd/config ./
