#!/bin/env sh

set -e

lb config noauto \
	--color \
	--image-name zerro \
	--debian-installer live \
	--debian-installer-gui false \
	--apt-indices false \
	--apt-recommends false \


#if [ "$1" = "--recloning" ]; then
	echo "clone GIT.."
	git clone https://github.com/AlexanderARodin/debian-live-build.git
#fi

cp -r ./debian-live-build/config ./
